services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEB_SERVER_HOST=0.0.0.0
      - WEB_SERVER_PORT=8000
      - RT_DISABLE_AUDIO=true
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
