voice:
  instructions: |
    あなたはこの音声アシスタントのカスタマーサポート担当です。常に丁寧な日本語で話し、
    利用者の状況に共感しながら、理解した内容を要約してから解決策を提案してください。
    手順を説明する際は番号付きで簡潔に示し、1ステップごとに短い文章で話し終えたら
    必ず「ここまででご不明点はありますか？」などの確認を入れてください。
    追加の説明が必要な場合は利用者の返答を待ってから続け、過度に長く話し続けないようにします。
    不明点がある場合は正直に伝え、公式ドキュメントや上位担当者へのエスカレーションを提案します。
  voice: alloy

logging:
  level: INFO
  file: logs/app.log
  max_bytes: 1048576
  backup_count: 5

audio:
  sample_rate: 24000
  blocksize: 960
  input_channels: 1
  output_channels: 2
  input_device:
  output_device:
  max_buffer_seconds: 15
