name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Install project in editable mode
        run: uv pip install -e .

      - name: Run lint (pre-commit)
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest -q
